// The Tao Te Ching
// by Laozi
// Translation by Stephen Mitchell

var passages = [
"The tao that can be told is not the eternal Tao",
"The name that can be named is not the eternal Name.",
"The unnamable is the eternally real.",
"Naming is the origin of all particular things.",
"Free from desire, you realize the mystery.",
"Caught in desire, you see only the manifestations.",
"Yet mystery and manifestations arise from the same source. This source is called darkness.",
"Darkness within darkness. The gateway to all understanding.",
"When people see some things as beautiful, other things become ugly.",
"When people see some things as good, other things become bad.",
"Being and non-being create each other.",
"Difficult and easy support each other.",
"Long and short define each other.",
"High and low depend on each other.",
"Before and after follow each other.",
"Therefore the Master acts without doing anything and teaches without saying anything.",
"Things arise and she lets them come; things disappear and she lets them go.",
"She has but doesn't possess, acts but doesn't expect.",
"When her work is done, she forgets it. That is why it lasts forever.",
"If you overesteem great men, people become powerless.",
"If you overvalue possessions, people begin to steal.",
"The Master leads by emptying people's minds and filling their cores, by weakening their ambition and toughening their resolve.",
"He helps people lose everything they know, everything they desire, and creates confusion in those who think that they know.",
"Practice not-doing, and everything will fall into place.",
"The Tao is like a well: used but never used up.",
"It is like the eternal void: filled with infinite possibilities.",
"It is hidden but always present.",
"I don't know who gave birth to it. It is older than God.",
"The Tao doesn't take sides; it gives birth to both good and evil.",
"The Master doesn't take sides; she welcomes both saints and sinners.",
"The Tao is like a bellows: it is empty yet infinitely capable.",
"The more you use it, the more it produces;",
"the more you talk of it, the less you understand.",
"Hold on to the center.",
"The Tao is called the Great Mother: empty yet inexhaustible, it gives birth to infinite worlds.",
"It is always present within you. You can use it any way you want.",
"The Tao is infinite, eternal.",
"Why is it eternal? It was never born; thus it can never die.",
"Why is it infinite? It has no desires for itself; thus it is present for all beings.",
"The Master stays behind; that is why she is ahead.",
"She is detached from all things; that is why she is one with them.",
"Because she has let go of herself, she is perfectly fulfilled.",
"The supreme good is like water, which nourishes all things without trying to.",
"It is content with the low places that people disdain. Thus it is like the Tao.",
"In dwelling, live close to the ground.",
"In thinking, keep to the simple.",
"In conflict, be fair and generous.",
"In governing, don't try to control.",
"In work, do what you enjoy.",
"In family life, be completely present.",
"When you are content to be simply yourself and don't compare or compete, everybody will respect you.",
"Fill your bowl to the brim and it will spill.",
"Keep sharpening your knife and it will blunt.",
"Chase after money and security and your heart will never unclench.",
"Care about people's approval and you will be their prisoner.",
"Do your work, then step back. The only path to serenity.",
"Can you coax your mind from its wandering and keep to the original oneness?",
"Can you let your body become supple as a newborn child's?",
"Can you cleanse your inner vision until you see nothing but the light?",
"Can you love people and lead them without imposing your will?",
"Can you deal with the most vital matters by letting events take their course?",
"Can you step back from you own mind and thus understand all things?",
"Giving birth and nourishing, having without possessing, acting with no expectations, leading and not trying to control: this is the supreme virtue.",
];

window.onload = function() {
  var passage = passages[Math.floor(Math.random() * passages.length)];
  var tao = document.getElementById('tao');
  tao.insertAdjacentHTML('afterbegin', '<p>' + passage + '</p>');
}